ARG VERSION=alpine3.16
#3.9-slim
FROM python:$VERSION

ARG COMMIT_SHA=main
ARG CREATED=""

LABEL \
    org.opencontainers.image.created="$CREATED" \
    org.opencontainers.image.authors="Mariano Alesci" \
    org.opencontainers.image.url=https://github.com/malesci/wasabi \
    org.opencontainers.image.documentation=https://github.com/malesci/wasabi/README.md \
    org.opencontainers.image.source=https://github.com/malesci/wasabi \
    org.opencontainers.image.revision=$COMMIT_SHA \
    org.opencontainers.image.vendor="Mariano Alesci" \
    org.opencontainers.image.licenses=MIT \
    org.opencontainers.image.ref.name=wasabi \
    org.opencontainers.image.title="wasabi container" \
    org.opencontainers.image.description="wasabi built in a tiny Alpine image"

# Set the SHELL option -o pipefail before RUN with a pipe in
SHELL ["/bin/sh", "-o", "pipefail", "-c"]


# Installs latest Chromium package.
RUN set -ex \
    && apk upgrade --no-cache --available \
    && apk add --no-cache \
      chromium \
      chromium-chromedriver

# Set display port as an environment variable
ENV DISPLAY=:99

# Create a nonroot user
RUN mkdir -p /usr/src/app \
    && adduser -D nonroot
WORKDIR /usr/src/app

ENV CHROME_BIN=/usr/bin/chromium-browser \
    CHROME_PATH=/usr/lib/chromium/
ENV PATH="/usr/src/app/.local/bin:${PATH}"

# Copy wasabi folder
COPY wasabi .

COPY entrypoint.sh .
RUN chmod +x ./entrypoint.sh

# Now that the OS has been updated to include required packages, update ownership and then switch to nonroot user
RUN chown -R nonroot:nonroot /usr/src/app
USER nonroot

# Install additional Python requirements
RUN pip install -r ./requirements.txt

CMD [ "./entrypoint.sh" ]
